name: app_losdealla
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_inappwebview: ^6.1.5
  youtube_player_flutter: ^9.1.3
  flutter_secure_storage: ^9.0.0
  supabase_flutter: ^2.5.6
  flutter_native_splash: ^2.4.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ruedadeconocimientos.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ruedadeconocimientos.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/imgsuscriptores/
    - assets/imgcasino/
    - assets/imgminis/miniyf/
    - assets/imgminis/minicasino/

flutter_native_splash:
  color: "#F3E5F5"
  android_12:
    color: "#F3E5F5"
    icon_background_color: "#F3E5F5"
    fullscreen: true